// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.ConditionalCommand;
import frc.robot.Robot;


/**
 *
 */
public class MyDriveToggleShifter extends ConditionalCommand {

    public MyDriveToggleShifter() {
      //super(new Auto_12_3_1_Deliver_Left_Scale_90_To_Plate(), new Auto_00_Reach_BaseLine());
      //super(new Auto_12_3_1_Deliver_Left_Scale_45_To_Plate(), new Auto_00_Reach_BaseLine());
      super(new MyDrive_ShiftHigh(), new MyDrive_ShiftLow());
    }

    @Override
    protected boolean condition(){
    	if(Robot.myDriveTrain.my_GetIsCurrentGearHigh()){
    		return false;
        }else {
        	return true;
        }
    }
}
